version: '3'
services:
  hls:
    build: ./hls/
    ports:
      - "1935:1935"
    volumes:
      - "./data:/data"

  nginx:
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - "./data:/data"
